{% set name = "segyio" %}
{% set version = "1.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/equinor/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9b1967740f620b20325be0312d589a865c716128f5711a8928bc2cd9a881426

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - numpy
    - python
    - pip
    - scikit-build
    - setuptools
    - setuptools_scm
    - pytest
    - pytest-runner
  run:
    - numpy
    - python

test:
  imports:
    - segyio

about:
  home: https://github.com/equinor/segyio
  license: LGPL-3.0-only
  license_family: GPL
  license_file: License.md
  summary: 'Simple and fast SEG-Y I/O'

  description: |
    segyio is a fast and practical library for reading and writing seismic data
    in SEG-Y format. segyio is random access oriented for modern computers with
    simple read/write primitives on lines.
  doc_url: https://segyio.readthedocs.io/
  dev_url: https://github.com/equinor/segyio

extra:
  recipe-maintainers:
    - jokva
