{% set name = "segyio" %}
{% set version = "1.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/equinor/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 43da840bcfa3e4d5864ab27cccf6362f1075c2667cbb79b80320ef3a5e363e90

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - pytest
    - pytest-runner
    - numpy
  run:
    - python
    - numpy

test:
  imports:
    - segyio

about:
  home: https://github.com/equinor/segyio
  license: LGPL-3.0
  license_family: GPL
  license_file: License.md
  summary: 'Simple and fast SEG-Y I/O'

  description: |
    segyio is a fast and practical library for reading and writing seismic data
    in SEG-Y format. segyio is random access oriented for modern computers with
    simple read/write primitives on lines.
  doc_url: http://segyio.readthedocs.io/
  dev_url: https://github.com/equinor/segyio

extra:
  recipe-maintainers:
    - jokva
