{% set name = "segyio" %}
{% set version = "1.8.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/equinor/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4b8883c2d3bc86d69d81be267c4eaedc2d244f4d083fba2872915da7e37ede03

build:
  number: 1
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - pytest
    - pytest-runner
    - numpy
    - scikit-build
  run:
    - python
    - numpy

test:
  imports:
    - segyio

about:
  home: https://github.com/equinor/segyio
  license: LGPL-3.0
  license_family: GPL
  license_file: License.md
  summary: 'Simple and fast SEG-Y I/O'

  description: |
    segyio is a fast and practical library for reading and writing seismic data
    in SEG-Y format. segyio is random access oriented for modern computers with
    simple read/write primitives on lines.
  doc_url: http://segyio.readthedocs.io/
  dev_url: https://github.com/equinor/segyio

extra:
  recipe-maintainers:
    - jokva
