travis:
  secure:
    BINSTAR_TOKEN: Sf49bWel46N+OSm4DvxHORRQCNiPYb41/6h6+Vdr6PkBq8ofRC6XW/tJ53s8yU1QARHA+CmGGkDuSKKX5fwUkkoo37SiaJtPeu6QL0UzrBqCOcMBS5Mltu1MUv9q9jJhxqt4ptoZlCT8JrYTi+uF6Vhk8AqCIRHI9Gmw9Zvrfrd5UaOgFdSYfMdB6SxhVD1N9AwAZ4zvJu7nIqAqPlTwfYCzmxapjPW6WxyIir6a06p9A5SAoXVfCdAQ/DFFzt5QzOY3K2VRWJLkvicXZ1YJ17ZBXwLjwXF9xly7EYRl6xzNGBn33m2BvgyDN89TmFL/vOpwty7mrMwFZUjcnseGsAyxPIqchh+HVyitvK05VNDCeWAG3QqCw3cNO5gvOWKnbLXsCFk4hCsWnWYxsjydlXMcA7uvsAuPKYMHd40+ruYXoZTevLjDXs2+j9Y+DYm9P/SZHUUTGuAulCVBr+l4K/ZpDvuGbIZJXBQ3/iphFHesa0pKoo5Q9Q1NrZTeNb8o1Q4BQzVWlpQ5buOL/k2SiLu/QfX53rod+KbnI8TTWDBu0HBN9F3zahJI/zkY2Yb970HQNFS3SpxJT8whdvzfHDedUSiWb0E5kwPhXroKygsR+zkPfqkL8oMfxEy2ebZghulELm/ht1bxrc4T0xqaiwkGLYqHIfCH3ws8w3BzAes=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  linux: azure
  osx: azure
  win: appveyor
  linux_ppc64le: None
  linux_aarch64: None